"""Add CNIC to students

Revision ID: 0fab6b8c15bc
Revises: c8dbcdabd3a4
Create Date: 2026-08-21 23:09:39.423468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fab6b8c15bc'
down_revision = 'c8dbcdabd3a4'

depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnic', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('cnic')

    # ### end Alembic commands ###
