"""Remove class_id from Subject

Revision ID: 3924956dbb33
Revises: fffee24bc260
Create Date: 2026-08-05 17:44:47.681461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3924956dbb33'
down_revision = 'fffee24bc260'

depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_subjects_class_id_classes', 'classes', ['class_id'], ['id'])

    # ### end Alembic commands ###
