"""Add managed_class_id to Teacher

Revision ID: 67fda7be9503
Revises: 0cf55cde3818
Create Date: 2026-08-01 11:53:06.000445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fda7be9503'
down_revision = '0cf55cde3818'

depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('managed_class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_teacher_managed_class_id", 'classes', ['managed_class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('managed_class_id')

    # ### end Alembic commands ###
