"""Add guardian fields to students

Revision ID: c8dbcdabd3a4
Revises: 3924956dbb33
Create Date: 2026-08-18 00:24:05.930202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8dbcdabd3a4'
down_revision = '3924956dbb33'

depends_on = None


def upgrade():
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_attendance_subject_id', 'subjects', ['subject_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=30), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_teacher_managed_class_id'), type_='foreignkey')
        batch_op.drop_column('managed_class_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('managed_class_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_teacher_managed_class_id'), 'classes', ['managed_class_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('guardian_phone')
        batch_op.drop_column('guardian_name')

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subject_id')

    
    # ### end Alembic commands ###
