"""Create TeacherSubject model

Revision ID: fffee24bc260
Revises: 67fda7be9503
Create Date: 2026-08-03 22:51:09.986526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fffee24bc260'
down_revision = '67fda7be9503'

depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_teacher_subject_school", 'schools', ['school_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_subjects', schema=None) as batch_op:
        batch_op.drop_constraint("fk_teacher_subject_school", type_='foreignkey')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
