from .role import Role
from .user import User
from .school import School
from .school_admin import SchoolAdmin
from .class_model import Class
from .section import Section
from .subject import Subject
from .teacher import Teacher
from .student import Student
from .parent import Parent
from .parent_student import ParentStudent
from .teachersubject import TeacherSubject
from .attendance import Attendance
from .exam import Exam
from .result import Result
from .fee_structure import FeeStructure
from .fee_payment import FeePayment
from .timetable import Timetable
from .assignment import Assignment
from .assignment_submission import AssignmentSubmission
from .notice import Notice